// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Uw_SXbqAMMlk3plGKRki2TvaWt9Zuqk',
    appId: '1:405338951910:web:0beffb675caaabe317ab27',
    messagingSenderId: '405338951910',
    projectId: 'pharmalink-6d256',
    authDomain: 'pharmalink-6d256.firebaseapp.com',
    storageBucket: 'pharmalink-6d256.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNFI4dlAMwY5ZEoe1fl4WbBmhYpfokdJc',
    appId: '1:405338951910:android:912582bc2f99401f17ab27',
    messagingSenderId: '405338951910',
    projectId: 'pharmalink-6d256',
    storageBucket: 'pharmalink-6d256.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApt7Ak_O7bYH2AEhsHa2YHa7-utp8uQmQ',
    appId: '1:405338951910:ios:c04759c92696fc5c17ab27',
    messagingSenderId: '405338951910',
    projectId: 'pharmalink-6d256',
    storageBucket: 'pharmalink-6d256.firebasestorage.app',
    iosBundleId: 'com.example.pharmalink',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApt7Ak_O7bYH2AEhsHa2YHa7-utp8uQmQ',
    appId: '1:405338951910:ios:c04759c92696fc5c17ab27',
    messagingSenderId: '405338951910',
    projectId: 'pharmalink-6d256',
    storageBucket: 'pharmalink-6d256.firebasestorage.app',
    iosBundleId: 'com.example.pharmalink',
  );
}
